name: api_client
description: A client to interact with the Dart Frog API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  api_models:
    path: ../api_models
  dio: ^5.7.0
  meta: ^1.15.0
  # TODO: remove passkit
  passkit: ^0.0.10
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
