name: api_client
description: A client to interact with the Dart Frog API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  api_models:
    path: ../api_models
  dio: ^5.7.0
  meta: ^1.15.0
  # TODO: remove passkit
  passkit: ^1.1.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^10.0.0-rc.2
