name: pass_data_source
description: A data source to manage passes.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  api_models:
    path: ../../../packages/api_models
  db_client:
    path: ../db_client
  passkit: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  dart_frog_lint: ^0.1.1
  mocktail: ^1.0.4
  test: ^1.25.7
