name: db_client
description: A client to interact with the database.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  api_models:
    path: ../../../packages/api_models
  collection: ^1.19.0
  hive_ce: ^2.6.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  hive_ce_generator: ^1.7.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^10.0.0-rc.2
