name: api
description: A Dart Frog API to manage pass generation.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  api_models:
    path: ../packages/api_models
  dart_frog: ^1.2.3
  dart_frog_auth: ^1.2.1
  db_client:
    path: packages/db_client
  pass_data_source:
    path: packages/pass_data_source
  user_repository:
    path: packages/user_repository

dev_dependencies:
  dart_frog_lint: ^0.1.1
  meta: ^1.16.0
  mocktail: ^1.0.0
  test: ^1.19.2
