name: api
description: A Dart Frog API to manage pass generation.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  api_models:
    path: ../packages/api_models
  basic_utils: ^5.7.0
  collection: ^1.19.0
  crypto: ^3.0.5
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  db_client:
    path: packages/db_client
  http: ^1.2.2
  meta: ^1.16.0
  mime: ^1.0.6
  pass_data_source:
    path: packages/pass_data_source
  path: ^1.9.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
