name: api

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.5.0
      coverage_excludes: "**/*.g.dart"
      working_directory: api
      analyze_directories: "routes test lib"